export { default as HeaderImg } from './IMG-20230608-WA0015.jpg'
export { default as Trouve } from './trouve.png'
export { default as Foodify } from './foodify.png'
export { default as Bic } from './bic.png'
export { default as BicAdmin } from './bic-admin.png'
export { default as AntiSapa } from './anti-sapa.png'
