export { default as Memoji } from './82342749.png'
export { default as Trouve } from './trouve.png'
export { default as Foodify } from './foodify.png'
export { default as Bic } from './bic.png'
export { default as BicAdmin } from './bic-admin.png'
export { default as AntiSapa } from './anti-sapa.png'
export { default as Portrait } from './portrait.png'
